version: "3.8"

services:
  web:
    build: .
    ports:
      - "8501:8501"
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - USER_DOCS_DIR=/app/Documents
    volumes:
      # 🔴 BULLETPROOF PATH: Ye aapke project ke andar hi folder banayega
      - ./Rainbow_ERP_Bills:/app/Documents
